[project]
name = "winsb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psutil>=6.1.1",
    "pyside6>=6.8.1.1",
    "qtmodern>=0.2.0",
]
